import './globals.css'

import { Inter } from 'next/font/google'
import { Navegation } from '@/app/components/Navegation'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className} >
        <Navegation />
        <div className="background">

          {children}

        </div>
      </body>
    </html>
  )
}
